apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "6"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"6"},"creationTimestamp":"2022-10-31T21:55:45Z","generation":7,"labels":{"app":"hello-world-rest-api"},"name":"hello-world-rest-api","namespace":"default","resourceVersion":"13510891","uid":"7ec59183-11be-4972-be8c-48d8b7889deb"},"spec":{"progressDeadlineSeconds":600,"replicas":3,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"hello-world-rest-api"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"hello-world-rest-api"}},"spec":{"containers":[{"image":"in28min/hello-world-rest-api:0.0.1.RELEASE","imagePullPolicy":"IfNotPresent","name":"hello-world-rest-api","resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30}}},"status":{"availableReplicas":3,"conditions":[{"lastTransitionTime":"2022-11-12T08:04:33Z","lastUpdateTime":"2022-11-12T08:04:33Z","message":"Deployment has minimum availability.","reason":"MinimumReplicasAvailable","status":"True","type":"Available"},{"lastTransitionTime":"2022-10-31T21:55:45Z","lastUpdateTime":"2022-11-20T20:26:50Z","message":"ReplicaSet \"hello-world-rest-api-7d8bc79659\" has successfully progressed.","reason":"NewReplicaSetAvailable","status":"True","type":"Progressing"}],"observedGeneration":7,"readyReplicas":3,"replicas":2,"updatedReplicas":3}}
  creationTimestamp: "2022-10-31T21:55:45Z"
  generation: 8
  labels:
    app: hello-world-rest-api
  name: hello-world-rest-api
  namespace: default
  resourceVersion: "13519316"
  uid: 7ec59183-11be-4972-be8c-48d8b7889deb
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: hello-world-rest-api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hello-world-rest-api
    spec:
      containers:
        - image: in28min/hello-world-rest-api:0.0.1.RELEASE
          imagePullPolicy: IfNotPresent
          name: hello-world-rest-api
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 3
  conditions:
    - lastTransitionTime: "2022-11-12T08:04:33Z"
      lastUpdateTime: "2022-11-12T08:04:33Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2022-10-31T21:55:45Z"
      lastUpdateTime: "2022-11-20T20:26:50Z"
      message: ReplicaSet "hello-world-rest-api-7d8bc79659" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
  observedGeneration: 8
  readyReplicas: 3
  replicas: 3
  updatedReplicas: 3

  ---
apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
  creationTimestamp: "2022-11-08T22:02:44Z"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: hello-world-rest-api
  name: hello-world-rest-api
  namespace: default
  resourceVersion: "5804801"
  uid: bfd4db09-9897-412a-bde7-c7d102179afc
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.100.8.127
  clusterIPs:
  - 10.100.8.127
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31436
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: hello-world-rest-api
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 34.68.8.190

